/**
 * One-Click Publish Panel
 * Lets the journalist publish their interview article to WordPress, Medium,
 * Substack, or generate a PDF press release — all from the interview studio.
 */

import { useState } from "react";
import {
  FileText,
  Globe,
  BookOpen,
  Mail,
  Download,
  Loader2,
  CheckCircle,
  AlertCircle,
  Send,
} from "lucide-react";

interface PublishPanelProps {
  transcript: string;
  storyTitle: string;
  journalistName: string;
  outlet: string;
  coachingSummary?: any;
  tags?: string[];
}

type Platform = "wordpress" | "medium" | "substack" | "pdf";

export function PublishPanel({
  transcript,
  storyTitle,
  journalistName,
  outlet,
  coachingSummary,
  tags,
}: PublishPanelProps) {
  const [platform, setPlatform] = useState<Platform>("pdf");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [credentials, setCredentials] = useState({
    wpUrl: "",
    wpUser: "",
    wpAppPassword: "",
    mediumToken: "",
    substackEmail: "",
  });

  const publish = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          platform,
          transcript,
          storyTitle,
          journalistName,
          outlet,
          coachingSummary,
          tags,
          ...credentials,
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Publishing failed");
      setResult(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result?.html) return;
    // Open a print-friendly window
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${storyTitle}</title>
          <style>
            body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #1a1a1a; }
            h1 { font-size: 28px; border-bottom: 2px solid #333; padding-bottom: 10px; }
            blockquote { border-left: 4px solid #ccc; padding-left: 16px; margin: 16px 0; font-style: italic; color: #555; }
            .byline { color: #666; font-size: 14px; margin-bottom: 24px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #888; }
            @media print { body { margin: 0; } }
          </style>
        </head>
        <body>
          <div class="byline">By ${journalistName}, ${outlet} — ${new Date().toLocaleDateString()}</div>
          ${result.html}
          <div class="footer">
            <p>Generated by AI Journalist Studio — ${new Date().toISOString()}</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  const platforms: { id: Platform; label: string; icon: typeof Globe; color: string }[] = [
    { id: "pdf", label: "PDF Press Release", icon: FileText, color: "text-red-600" },
    { id: "wordpress", label: "WordPress", icon: Globe, color: "text-blue-600" },
    { id: "medium", label: "Medium", icon: BookOpen, color: "text-green-600" },
    { id: "substack", label: "Substack", icon: Mail, color: "text-orange-600" },
  ];

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-5">
      <div className="flex items-center gap-2">
        <Send className="h-5 w-5 text-indigo-600" />
        <h3 className="text-lg font-semibold">One-Click Publish</h3>
      </div>

      {/* Platform selector */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {platforms.map((p) => {
          const Icon = p.icon;
          return (
            <button
              key={p.id}
              onClick={() => setPlatform(p.id)}
              className={`flex flex-col items-center gap-2 p-3 rounded-lg border-2 transition ${
                platform === p.id
                  ? "border-indigo-600 bg-indigo-50"
                  : "border-gray-200 hover:border-gray-300"
              }`}
            >
              <Icon className={`h-6 w-6 ${platform === p.id ? "text-indigo-600" : p.color}`} />
              <span className="text-xs font-medium">{p.label}</span>
            </button>
          );
        })}
      </div>

      {/* Platform-specific credentials */}
      {platform === "wordpress" && (
        <div className="space-y-2 p-4 bg-gray-50 rounded-lg">
          <p className="text-xs font-semibold text-gray-600 mb-2">WordPress Credentials</p>
          <input
            type="text"
            placeholder="Site URL (https://yoursite.com)"
            value={credentials.wpUrl}
            onChange={(e) => setCredentials({ ...credentials, wpUrl: e.target.value })}
            className="w-full text-sm border border-gray-300 rounded px-3 py-2"
          />
          <div className="grid grid-cols-2 gap-2">
            <input
              type="text"
              placeholder="Username"
              value={credentials.wpUser}
              onChange={(e) => setCredentials({ ...credentials, wpUser: e.target.value })}
              className="text-sm border border-gray-300 rounded px-3 py-2"
            />
            <input
              type="password"
              placeholder="App Password"
              value={credentials.wpAppPassword}
              onChange={(e) => setCredentials({ ...credentials, wpAppPassword: e.target.value })}
              className="text-sm border border-gray-300 rounded px-3 py-2"
            />
          </div>
          <p className="text-xs text-gray-500">Create an App Password in WordPress → Users → Application Passwords.</p>
        </div>
      )}

      {platform === "medium" && (
        <div className="space-y-2 p-4 bg-gray-50 rounded-lg">
          <p className="text-xs font-semibold text-gray-600 mb-2">Medium Integration Token</p>
          <input
            type="password"
            placeholder="Medium Integration Token"
            value={credentials.mediumToken}
            onChange={(e) => setCredentials({ ...credentials, mediumToken: e.target.value })}
            className="w-full text-sm border border-gray-300 rounded px-3 py-2"
          />
          <p className="text-xs text-gray-500">Get your token at medium.com/me/settings/security — Integration tokens.</p>
        </div>
      )}

      {platform === "substack" && (
        <div className="space-y-2 p-4 bg-gray-50 rounded-lg">
          <p className="text-xs text-gray-500">
            Substack doesn't have a public API. We'll generate the article and open a pre-filled email draft
            for you to paste into Substack's editor.
          </p>
          <input
            type="email"
            placeholder="Your Substack post email (optional)"
            value={credentials.substackEmail}
            onChange={(e) => setCredentials({ ...credentials, substackEmail: e.target.value })}
            className="w-full text-sm border border-gray-300 rounded px-3 py-2"
          />
        </div>
      )}

      {error && (
        <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
          <AlertCircle className="h-4 w-4" /> {error}
        </div>
      )}

      {result && (
        <div className="space-y-3">
          <div className="flex items-center gap-2 p-3 bg-green-50 border border-green-200 rounded-lg text-green-700 text-sm">
            <CheckCircle className="h-4 w-4" />
            {result.url ? (
              <a href={result.url} target="_blank" rel="noopener" className="font-medium underline">
                Published! View it here →
              </a>
            ) : (
              <span>Article generated successfully!</span>
            )}
          </div>
          {result.editUrl && (
            <a href={result.editUrl} target="_blank" rel="noopener" className="text-sm text-blue-600 hover:underline block">
              Edit in WordPress →
            </a>
          )}
          {result.instructions && (
            <p className="text-sm text-gray-600">{result.instructions}</p>
          )}
          {result.html && platform === "pdf" && (
            <button
              onClick={downloadPDF}
              className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-medium hover:bg-red-700"
            >
              <Download className="h-4 w-4" /> Download / Print PDF
            </button>
          )}
        </div>
      )}

      <button
        onClick={publish}
        disabled={loading || !transcript.trim()}
        className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 disabled:opacity-50 transition"
      >
        {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
        {loading ? "Generating & Publishing..." : `Publish to ${platforms.find((p) => p.id === platform)?.label}`}
      </button>
    </div>
  );
}

export default PublishPanel;
